version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ../data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ../data/ollama:/root/.ollama

  api:
    build:
      context: ..
      dockerfile: infra/dockerfiles/api.Dockerfile
    environment:
      CODEX_CONFIG: /app/configs/dev.yaml
      QDRANT_URL: http://qdrant:6333
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - qdrant
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ..:/app:delegated
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  grafana-data:
